name: run workflows for all IDEs

on:
  push:
    branches:
      - master
    paths:
      - "image/**" # run the action when: the image has been modified
      - ".github/workflows/**" # run the action when: the workflow has been modified
jobs:
  build-phpstorm:
    uses: aaronflorey/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: PhpStorm
      IDE_SHORT: phpstorm
      IDE_CODE: webide
      IDE_VERSION: 2024.3
