name: build & push

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 14 * * 0

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        builds:
          - { IDE: PhpStorm, IDE_SHORT: phpstorm, IDE_CODE: webide }
        version:
          - 2024.3
          - 2024.2
          - 2024.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: aaronflorey
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./image
          build-args: |
            IDE=${{ matrix.builds.IDE }}
            IDE_SHORT=${{ matrix.builds.IDE_SHORT }}
            IDE_CODE=${{ matrix.builds.IDE_CODE }}
            IDE_VERSION=${{ matrix.version }}
          tags: |
            ghcr.io/aaronflorey/indexer:${{ matrix.builds.IDE_SHORT }}-${{ matrix.version }}
          push: true
